Document: sanepic
Title: Debian sanepic Manual
Author: <insert document author here>
Abstract: This manual describes what sanepic is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sanepic/sanepic.sgml.gz

Format: postscript
Files: /usr/share/doc/sanepic/sanepic.ps.gz

Format: text
Files: /usr/share/doc/sanepic/sanepic.text.gz

Format: HTML
Index: /usr/share/doc/sanepic/html/index.html
Files: /usr/share/doc/sanepic/html/*.html
